import { useState, useEffect, useRef } from 'react'
import './App.css'

function App() {
  const [messages, setMessages] = useState([])
  const [input, setInput] = useState('')
  const [model, setModel] = useState('qwen')
  const [loading, setLoading] = useState(false)
  const [brdTemplate, setBrdTemplate] = useState('')
  const [collectedFields, setCollectedFields] = useState({})
  const messagesEndRef = useRef(null)

  // Load BRD template on mount
  useEffect(() => {
    fetch('/brd-template')
      .then(res => res.json())
      .then(data => setBrdTemplate(data.content))
      .catch(err => console.error('Failed to load template:', err))
  }, [])

  // Scroll to bottom on new messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])

  const handleSend = async () => {
    if (!input.trim() || loading) return

    const userMessage = input.trim()
    setInput('')
    setLoading(true)

    // Add user message
    setMessages(prev => [...prev, { role: 'user', content: userMessage }])

    try {
      const response = await fetch('/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: userMessage,
          model: model,
          history: messages
        })
      })

      const data = await response.json()
      setMessages(prev => [...prev, { role: 'ai', content: data.response }])
    } catch (err) {
      setMessages(prev => [...prev, {
        role: 'ai',
        content: 'Sorry, I encountered an error. Make sure Ollama is running with the qwen or gemma model.'
      }])
    }

    setLoading(false)
  }

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSend()
    }
  }

  const handleExport = async () => {
    // For now, export a simple summary
    const summary = `# Draft BRD - ${new Date().toLocaleDateString()}

## Collected Information

${messages.map(m => `### ${m.role === 'user' ? 'User' : 'AI'}
${m.content}
`).join('\n')}

---
*Generated by Ask Data - BRD Collection Chatbot*
`

    try {
      const response = await fetch('/export-brd', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ brd_content: summary })
      })

      const data = await response.json()
      alert(`BRD exported to: ${data.file_path}`)
    } catch (err) {
      alert('Failed to export BRD')
    }
  }

  // Progress sections based on BRD template
  const progressSections = [
    { id: 'project', title: 'Project Overview', items: ['Name', 'Sponsor', 'Owner', 'Team', 'Timeline', 'Objective'] },
    { id: 'business', title: 'Business Background', items: ['Context', 'Pain Points', 'Business Value'] },
    { id: 'stakeholder', title: 'Stakeholder Analysis', items: ['Stakeholders', 'Interests', 'Expectations'] },
    { id: 'requirements', title: 'Core Requirements', items: ['Data Sources', 'Visualization', 'Insights', 'Non-functional'] },
    { id: 'constraints', title: 'Constraints & Risks', items: ['Resources', 'Timeline', 'Risks'] },
    { id: 'deliverables', title: 'Deliverables', items: ['List of deliverables'] }
  ]

  return (
    <div className="app">
      <header className="header">
        <h1>Ask Data - BRD Collection</h1>
        <div className="header-controls">
          <select
            className="model-selector"
            value={model}
            onChange={(e) => setModel(e.target.value)}
          >
            <option value="qwen">Qwen</option>
            <option value="gemma">Gemma</option>
          </select>
        </div>
      </header>

      <main className="main-content">
        <div className="chat-container">
          <div className="chat-messages">
            {messages.length === 0 && (
              <div className="message ai">
                <div className="message-header">AI Assistant</div>
                Hello! I'm your Product Manager assistant. I'll help you create a Business Requirements Document (BRD) for your data analysis project. Let's start by discussing your project. What is the name of your project?
              </div>
            )}
            {messages.map((msg, idx) => (
              <div key={idx} className={`message ${msg.role}`}>
                <div className="message-header">
                  {msg.role === 'user' ? 'You' : 'AI Assistant'}
                </div>
                {msg.content}
              </div>
            ))}
            {loading && (
              <div className="loading">
                <div className="spinner"></div>
                Thinking...
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          <div className="chat-input-container">
            <textarea
              className="chat-input"
              placeholder="Type your message..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyPress={handleKeyPress}
              rows={1}
            />
            <button
              className="send-button"
              onClick={handleSend}
              disabled={loading || !input.trim()}
            >
              Send
            </button>
          </div>
        </div>

        <aside className="progress-sidebar">
          <h3>BRD Progress</h3>
          {progressSections.map(section => (
            <div key={section.id} className="progress-section">
              <div className="progress-section-title">
                <span className="icon pending">○</span>
                {section.title}
              </div>
              <div className="progress-items">
                {section.items.map((item, idx) => (
                  <div key={idx} className="progress-item">{item}</div>
                ))}
              </div>
            </div>
          ))}

          <div className="export-section">
            <button className="export-button" onClick={handleExport}>
              Export Draft BRD
            </button>
          </div>
        </aside>
      </main>
    </div>
  )
}

export default App